# Codecov configuration for Blitzed
# Copyright 2025 Gibran Rodriguez <brangi000@gmail.com>

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 5%
        if_not_found: success
    patch:
      default:
        target: 80%
        threshold: 10%
        if_not_found: success

comment:
  layout: "header,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "benches/**/*"
  - "examples/**/*"
  - "target/**/*"