// Auto-generated by tools/train_vibration_classifier.py
// Model: 2-layer dense network for ESP32 vibration pattern classification
// Architecture: Dense(3, 32) + ReLU + Dense(32, 4)
// Input: [rms_x, rms_y, rms_z] — RMS acceleration per axis from MPU6050
// Total parameters: 260
// Quantized model size: 368 bytes
// Quantization: calibrated INT8 PTQ (output scales from activation statistics)

#ifndef BLITZED_MODEL_WEIGHTS_H
#define BLITZED_MODEL_WEIGHTS_H

#include <stdint.h>

// Layer 1: Dense(3, 32) + ReLU
#define LAYER1_INPUT_SIZE 3
#define LAYER1_OUTPUT_SIZE 32

// Weights stored row-major: layer1_weights[input_idx * LAYER1_OUTPUT_SIZE + output_idx]
static const int8_t layer1_weights[96] = {
    108, -50, -10, -68, -79, -52, -74, -115, 52, -7, -60, 18,
    96, -77, -74, -15, 2, -78, -56, -22, 74, -41, -44, -111,
    -128, -80, -58, -74, -9, -67, -55, -78, 90, 3, -78, -52,
    -72, -50, -108, -118, 48, 9, -64, -66, 113, -20, -71, -14,
    -24, -69, -72, -10, 32, -11, -70, -118, -98, -80, -58, -75,
    -18, -66, -56, -63, 81, -71, -79, -61, -41, -55, -84, -107,
    50, 19, -53, 11, 127, -30, -53, -106, 4, -64, -76, -37,
    68, -41, -43, -84, -111, -42, -45, -8, -23, -17, -66, -60
};

static const int32_t layer1_bias[32] = {
    -1477, -252, 72, 0, -308, 0, 11003, 17243, -5461, -621, 0, -760,
    -2130, -62, 0, 140, -536, 0, 0, 125, -1182, -428, 855, 16069,
    15008, -255, 71, -4, 4267, 1044, 0, 0
};

static const float layer1_weight_scale = 0.0124905160f;
static const int32_t layer1_weight_zero_point = -47;
// Calibrated output scale: maps post-ReLU activations to INT8 [0, 127]
static const float layer1_output_scale = 0.0437850056f;
static const int32_t layer1_output_zero_point = 0;

// Layer 2: Dense(32, 4)
#define LAYER2_INPUT_SIZE 32
#define LAYER2_OUTPUT_SIZE 4

// Weights stored row-major: layer2_weights[input_idx * LAYER2_OUTPUT_SIZE + output_idx]
static const int8_t layer2_weights[128] = {
    -118, 27, 96, 88, -13, 19, 32, 11, 6, 59, 18, 28,
    26, 36, 10, 45, 33, 16, 9, 10, 39, 30, 21, 18,
    83, 60, 23, -23, 103, 64, 7, -68, 4, -51, 24, 119,
    -20, 45, 45, 74, 19, 36, 17, 3, -27, 45, 25, 50,
    -128, 8, 90, 127, 3, 42, 50, 31, 34, 11, 26, 20,
    3, 62, 31, -1, 1, 27, 65, 55, 6, 28, 29, 13,
    25, 24, 32, 15, 0, 14, 35, 26, -90, 19, 58, 73,
    30, 27, 34, 58, 40, 45, 10, 33, 91, 67, 21, -63,
    112, 48, 0, -45, 22, 14, 18, 48, 19, 29, 41, 27,
    2, 45, 10, 5, 1, 50, 53, 18, 20, 4, 34, 5,
    43, 8, 3, 24, 10, 37, 45, 5
};

static const int32_t layer2_bias[4] = {
    889, 625, 186, -1700
};

static const float layer2_weight_scale = 0.0177550902f;
static const int32_t layer2_weight_zero_point = 26;
// Calibrated output scale: maps output logits to INT8 [-128, 127]
static const float layer2_output_scale = 0.2580216104f;
static const int32_t layer2_output_zero_point = 30;

// Input quantization parameters
// Normalize each RMS value by INPUT_NORM_FACTOR (12.0g) before quantizing
#define INPUT_SCALE 0.0078740157f
#define INPUT_ZERO_POINT 0
#define INPUT_NORM_FACTOR 12.0f

// Class labels
#define NUM_CLASSES 4
static const char* class_labels[NUM_CLASSES] = {
    "normal",
    "imbalance",
    "misalignment",
    "bearing_fault"
};

#endif // BLITZED_MODEL_WEIGHTS_H
