// Auto-generated by tools/train_hall_sensor_classifier.py
// Model: 2-layer dense network for ESP32 hall sensor classification
// Architecture: Dense(1, 16) + ReLU + Dense(16, 3)
// Total parameters: 83
// Quantized model size: 140 bytes

#ifndef BLITZED_MODEL_WEIGHTS_H
#define BLITZED_MODEL_WEIGHTS_H

#include <stdint.h>

// Layer 1: Dense(1, 16) + ReLU
#define LAYER1_INPUT_SIZE 1
#define LAYER1_OUTPUT_SIZE 16

static const int8_t layer1_weights[16] = {
    -51, -8, -61, -42, -11, 127, 32, -19, -81, -67, -92, 56,
    -128, -110, 66, 3
};

static const int32_t layer1_bias[16] = {
    9291, -749, 7830, -675, -136, 1897, -914, -2074, 11836, 12766, -1025, 11912,
    1472, -1044, 10989, 17530
};

static const float layer1_weight_scale = 0.0157799645f;
static const int32_t layer1_weight_zero_point = -11;
static const float layer1_output_scale = 0.0000618822f;
static const int32_t layer1_output_zero_point = 0;

// Layer 2: Dense(16, 3)
#define LAYER2_INPUT_SIZE 16
#define LAYER2_OUTPUT_SIZE 3

static const int8_t layer2_weights[48] = {
    8, -101, -35, -57, -61, -15, 11, -59, 40, -63, -20, -15,
    -28, -32, -61, -118, 127, -89, -93, -6, -5, -23, -14, -57,
    11, -115, 40, 15, -128, -35, -128, -55, 15, -4, 25, -120,
    -118, -98, 92, -114, -30, 74, -20, 68, -103, 50, -65, -104
};

static const int32_t layer2_bias[3] = {
    1299840, -649035, -650805
};

static const float layer2_weight_scale = 0.0118478953f;
static const int32_t layer2_weight_zero_point = -30;
static const float layer2_output_scale = 0.0000007332f;
static const int32_t layer2_output_zero_point = 0;

// Input quantization parameters
#define INPUT_SCALE 0.0039215686f
#define INPUT_ZERO_POINT 0
#define INPUT_MIN -200.0f
#define INPUT_MAX 200.0f

// Class labels
#define NUM_CLASSES 3
static const char* class_labels[NUM_CLASSES] = {
    "normal",
    "magnet_near",
    "magnet_far"
};

#endif // BLITZED_MODEL_WEIGHTS_H
