// Auto-generated by tools/train_temp_anomaly_detector.py
// Model: 2-layer dense network for ESP32 temperature anomaly detection
// Architecture: Dense(1, 16) + ReLU + Dense(16, 4)
// Total parameters: 84
// Quantized model size: 160 bytes

#ifndef BLITZED_MODEL_WEIGHTS_H
#define BLITZED_MODEL_WEIGHTS_H

#include <stdint.h>

// Layer 1: Dense(1, 16) + ReLU
#define LAYER1_INPUT_SIZE 1
#define LAYER1_OUTPUT_SIZE 16

static const int8_t layer1_weights[16] = {
    0, -80, -83, 53, -23, 127, 14, 20, 35, -33, -56, -18,
    -34, -128, -21, -26
};

static const int32_t layer1_bias[16] = {
    1773, 2129, 2271, -1909, -93, 394, 3514, 163, 242, 1177, 1314, -47,
    -197, 11813, -75, 1202
};

static const float layer1_weight_scale = 0.0212972778f;
static const int32_t layer1_weight_zero_point = -13;
static const float layer1_output_scale = 0.0240833638f;
static const int32_t layer1_output_zero_point = 0;

// Layer 2: Dense(16, 4)
#define LAYER2_INPUT_SIZE 16
#define LAYER2_OUTPUT_SIZE 4

static const int8_t layer2_weights[64] = {
    22, -9, 33, -1, -51, 80, 14, 28, -50, 88, 12, 14,
    -33, 16, 43, 78, 47, 32, 11, 29, -20, -113, 77, 126,
    49, -27, 35, 4, 40, 9, 43, 63, 19, -34, 11, 51,
    24, 40, -1, 42, -30, 44, 23, 26, 25, 0, -8, 24,
    22, -6, 29, 12, 78, 127, -38, -128, 34, 22, 28, 37,
    38, 44, 18, 12
};

static const int32_t layer2_bias[4] = {
    2051, -267, 138, -1923
};

static const float layer2_weight_scale = 0.0164966938f;
static const int32_t layer2_weight_zero_point = 15;
static const float layer2_output_scale = 0.0674766879f;
static const int32_t layer2_output_zero_point = 0;

// Input quantization parameters
// Temperatures are normalized by dividing by INPUT_MAX (120.0) before quantization.
// input_scale covers the full normalized range [INPUT_MIN/120, 1.0] mapped into INT8.
#define INPUT_SCALE 0.0085301837f
#define INPUT_ZERO_POINT 0
#define INPUT_MIN -10.0f
#define INPUT_MAX 120.0f

// Class labels
#define NUM_CLASSES 4
static const char* class_labels[NUM_CLASSES] = {
    "normal",
    "cold_warning",
    "hot_warning",
    "critical_overheat"
};

#endif // BLITZED_MODEL_WEIGHTS_H
