// Copyright 2025 Gibran Rodriguez <brangi000@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! ESP32-specific code generator
//!
//! Generates complete, compilable ESP-IDF v5.x projects with:
//! - Real INT8 quantized model weights
//! - Layer-by-layer inference kernel
//! - Proper CMakeLists.txt with idf_component_register
//! - Sensor integration boilerplate

use super::{CodeGenerator, GeneratedCode};
use crate::model::{LayerType, QuantizedLayerWeights, QuantizedModelWeights};
use crate::{Model, Result};
use std::path::Path;

/// ESP32 code generator
pub struct Esp32CodeGen;

impl Esp32CodeGen {
    #[must_use]
    pub const fn new() -> Self {
        Self
    }

    /// Generate a complete ESP-IDF project from quantized weights.
    ///
    /// This produces a project that compiles with `idf.py build` and
    /// runs real INT8 inference on the ESP32.
    pub fn generate_from_weights(
        &self,
        weights: &QuantizedModelWeights,
        output_dir: &Path,
    ) -> Result<GeneratedCode> {
        let main_dir = output_dir.join("main");
        std::fs::create_dir_all(&main_dir)?;

        // Generate all project files
        let project_cmake = self.gen_project_cmake();
        let main_cmake = self.gen_main_cmake();
        let sdkconfig = self.gen_sdkconfig_defaults();
        let weights_header = self.gen_weights_header(weights);
        let inference_header = self.gen_inference_header(weights);
        let inference_impl = self.gen_inference_impl(weights);
        let main_c = self.gen_main_c(weights);

        // Write files
        std::fs::write(output_dir.join("CMakeLists.txt"), &project_cmake)?;
        std::fs::write(main_dir.join("CMakeLists.txt"), &main_cmake)?;
        std::fs::write(output_dir.join("sdkconfig.defaults"), &sdkconfig)?;
        std::fs::write(main_dir.join("blitzed_model_weights.h"), &weights_header)?;
        std::fs::write(main_dir.join("blitzed_inference.h"), &inference_header)?;
        std::fs::write(main_dir.join("blitzed_inference.c"), &inference_impl)?;
        std::fs::write(main_dir.join("main.c"), &main_c)?;

        Ok(GeneratedCode {
            implementation_file: inference_impl,
            header_file: Some(weights_header),
            example_file: Some(main_c),
            build_config: Some(project_cmake),
            dependencies: vec!["ESP-IDF v5.x".to_string()],
        })
    }

    fn gen_project_cmake(&self) -> String {
        format!(
            r#"# Generated by Blitzed v{version}
# ESP-IDF project - build with: idf.py set-target esp32 && idf.py build

cmake_minimum_required(VERSION 3.16)

include($ENV{{IDF_PATH}}/tools/cmake/project.cmake)
project(blitzed_model)
"#,
            version = crate::VERSION
        )
    }

    fn gen_main_cmake(&self) -> String {
        format!(
            "# Generated by Blitzed v{}\n\
             idf_component_register(SRCS \"main.c\" \"blitzed_inference.c\"\n\
             {}INCLUDE_DIRS \".\")\n",
            crate::VERSION,
            "                       "
        )
    }

    fn gen_sdkconfig_defaults(&self) -> String {
        "# Generated by Blitzed\n\
         # ESP32 optimized for inference\n\
         CONFIG_ESP32_DEFAULT_CPU_FREQ_240=y\n\
         CONFIG_FREERTOS_HZ=1000\n\
         CONFIG_LOG_DEFAULT_LEVEL_INFO=y\n\
         CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE=4096\n"
            .to_string()
    }

    fn gen_weights_header(&self, weights: &QuantizedModelWeights) -> String {
        let mut out = format!(
            "// Generated by Blitzed v{}\n\
             // INT8 quantized model weights\n\
             \n\
             #ifndef BLITZED_MODEL_WEIGHTS_H\n\
             #define BLITZED_MODEL_WEIGHTS_H\n\
             \n\
             #include <stdint.h>\n\n",
            crate::VERSION
        );

        // Input quantization parameters
        out.push_str(&format!(
            "// Input quantization\n\
             #define INPUT_SCALE {:.10}f\n\
             #define INPUT_ZERO_POINT {}\n\
             #define INPUT_MIN {:.1}f\n\
             #define INPUT_MAX {:.1}f\n\n",
            weights.input_scale, weights.input_zero_point, weights.input_min, weights.input_max
        ));

        // Class labels
        out.push_str(&format!("#define NUM_CLASSES {}\n", weights.num_classes));
        out.push_str("static const char* class_labels[] = {");
        for (i, label) in weights.class_labels.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("\"{}\"", label));
        }
        out.push_str("};\n\n");

        // Per-layer weights, biases, and quantization parameters
        for layer in &weights.layers {
            out.push_str(&format!(
                "// {}: {}({}, {}){}\n",
                layer.name,
                match layer.layer_type {
                    LayerType::Dense => "Dense",
                    LayerType::Conv2d => "Conv2d",
                },
                layer.input_size,
                layer.output_size,
                if layer.has_relu { " + ReLU" } else { "" }
            ));
            out.push_str(&format!(
                "#define {name}_INPUT_SIZE {input}\n\
                 #define {name}_OUTPUT_SIZE {output}\n",
                name = layer.name.to_uppercase(),
                input = layer.input_size,
                output = layer.output_size
            ));

            // Weights array
            out.push_str(&format!(
                "static const int8_t {}_weights[{}] = {{\n    ",
                layer.name,
                layer.weights_int8.len()
            ));
            for (i, &w) in layer.weights_int8.iter().enumerate() {
                if i > 0 && i % 16 == 0 {
                    out.push_str("\n    ");
                }
                out.push_str(&format!("{}, ", w));
            }
            out.push_str("\n};\n");

            // Bias array
            out.push_str(&format!(
                "static const int32_t {}_bias[{}] = {{\n    ",
                layer.name,
                layer.bias_int32.len()
            ));
            for (i, &b) in layer.bias_int32.iter().enumerate() {
                if i > 0 && i % 8 == 0 {
                    out.push_str("\n    ");
                }
                out.push_str(&format!("{}, ", b));
            }
            out.push_str("\n};\n");

            // Quantization parameters
            out.push_str(&format!(
                "static const float {name}_weight_scale = {ws:.10}f;\n\
                 static const int32_t {name}_weight_zero_point = {wzp};\n\
                 static const float {name}_output_scale = {os:.10}f;\n\
                 static const int32_t {name}_output_zero_point = {ozp};\n\n",
                name = layer.name,
                ws = layer.weight_scale,
                wzp = layer.weight_zero_point,
                os = layer.output_scale,
                ozp = layer.output_zero_point,
            ));
        }

        out.push_str("#endif // BLITZED_MODEL_WEIGHTS_H\n");
        out
    }

    fn gen_inference_header(&self, weights: &QuantizedModelWeights) -> String {
        let first_input = weights.layers.first().map_or(1, |l| l.input_size);
        let last_output = weights.layers.last().map_or(1, |l| l.output_size);

        format!(
            "// Generated by Blitzed v{version}\n\
             #ifndef BLITZED_INFERENCE_H\n\
             #define BLITZED_INFERENCE_H\n\
             \n\
             #include <stdint.h>\n\
             \n\
             #define MODEL_INPUT_SIZE {input}\n\
             #define MODEL_OUTPUT_SIZE {output}\n\
             \n\
             int blitzed_model_init(void);\n\
             int blitzed_model_predict(const int8_t* input, int input_len, int8_t* output, int output_len);\n\
             int8_t blitzed_quantize_input(float raw_value);\n\
             float blitzed_dequantize_output(int8_t value);\n\
             int blitzed_argmax(const int8_t* output, int len);\n\
             \n\
             #endif // BLITZED_INFERENCE_H\n",
            version = crate::VERSION,
            input = first_input,
            output = last_output,
        )
    }

    fn gen_inference_impl(&self, weights: &QuantizedModelWeights) -> String {
        let mut out = format!(
            "// Generated by Blitzed v{}\n\
             // Real INT8 inference kernel\n\
             \n\
             #include \"blitzed_inference.h\"\n\
             #include \"blitzed_model_weights.h\"\n\
             #include <string.h>\n\n",
            crate::VERSION
        );

        // model_init
        out.push_str(
            "int blitzed_model_init(void) {\n\
             \x20\x20\x20\x20return 0; // Weights are const arrays, no dynamic init needed\n\
             }\n\n",
        );

        // model_predict - generate layer-by-layer inference
        out.push_str(
            "int blitzed_model_predict(const int8_t* input, int input_len, int8_t* output, int output_len) {\n\
             \x20\x20\x20\x20if (!input || !output) return -1;\n\n",
        );

        let num_layers = weights.layers.len();
        for (i, layer) in weights.layers.iter().enumerate() {
            let is_first = i == 0;
            let is_last = i == num_layers - 1;
            let input_var = if is_first {
                "input".to_string()
            } else {
                format!("hidden_{}", i - 1)
            };
            let input_len_expr = if is_first {
                "input_len".to_string()
            } else {
                format!("{}_OUTPUT_SIZE", weights.layers[i - 1].name.to_uppercase())
            };
            let prev_scale = if is_first {
                "INPUT_SCALE".to_string()
            } else {
                format!("{}_output_scale", weights.layers[i - 1].name)
            };

            match layer.layer_type {
                LayerType::Dense => {
                    if !is_last {
                        // Hidden layer: output to local buffer
                        out.push_str(&format!(
                            "    // {name}: Dense({inp}, {outp}){relu}\n\
                             \x20\x20\x20\x20int8_t hidden_{i}[{name_upper}_OUTPUT_SIZE];\n\
                             \x20\x20\x20\x20for (int j = 0; j < {name_upper}_OUTPUT_SIZE; j++) {{\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20int32_t acc = {name}_bias[j];\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20for (int k = 0; k < {name_upper}_INPUT_SIZE && k < {in_len}; k++) {{\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20acc += (int32_t){in_var}[k] * (int32_t){name}_weights[k * {name_upper}_OUTPUT_SIZE + j];\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20float fval = (float)acc * {prev_scale} * {name}_weight_scale;\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20int32_t q = (int32_t)(fval / {name}_output_scale) + {name}_output_zero_point;\n",
                            name = layer.name,
                            name_upper = layer.name.to_uppercase(),
                            inp = layer.input_size,
                            outp = layer.output_size,
                            relu = if layer.has_relu { " + ReLU" } else { "" },
                            i = i,
                            in_var = input_var,
                            in_len = input_len_expr,
                            prev_scale = prev_scale,
                        ));
                        if layer.has_relu {
                            out.push_str(&format!(
                                "        if (q < {name}_output_zero_point) q = {name}_output_zero_point; // ReLU\n",
                                name = layer.name
                            ));
                        }
                        out.push_str(&format!(
                            "        if (q > 127) q = 127;\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20if (q < -128) q = -128;\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20hidden_{i}[j] = (int8_t)q;\n\
                             \x20\x20\x20\x20}}\n\n",
                            i = i
                        ));
                    } else {
                        // Output layer: write to output buffer
                        out.push_str(&format!(
                            "    // {name}: Dense({inp}, {outp}) — output layer\n\
                             \x20\x20\x20\x20int out_len = {name_upper}_OUTPUT_SIZE < output_len ? {name_upper}_OUTPUT_SIZE : output_len;\n\
                             \x20\x20\x20\x20for (int j = 0; j < out_len; j++) {{\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20int32_t acc = {name}_bias[j];\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20for (int k = 0; k < {name_upper}_INPUT_SIZE; k++) {{\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20acc += (int32_t){in_var}[k] * (int32_t){name}_weights[k * {name_upper}_OUTPUT_SIZE + j];\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20}}\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20float fval = (float)acc * {prev_scale} * {name}_weight_scale;\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20int32_t q = (int32_t)(fval / {name}_output_scale) + {name}_output_zero_point;\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20if (q > 127) q = 127;\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20if (q < -128) q = -128;\n\
                             \x20\x20\x20\x20\x20\x20\x20\x20output[j] = (int8_t)q;\n\
                             \x20\x20\x20\x20}}\n\n",
                            name = layer.name,
                            name_upper = layer.name.to_uppercase(),
                            inp = layer.input_size,
                            outp = layer.output_size,
                            in_var = input_var,
                            prev_scale = prev_scale,
                        ));
                    }
                }
                LayerType::Conv2d => {
                    // Conv2d codegen can be added later; for now tiny models use Dense only
                    out.push_str(&format!(
                        "    // TODO: Conv2d layer '{}' — not yet supported in codegen\n\n",
                        layer.name
                    ));
                }
            }
        }

        out.push_str("    return 0;\n}\n\n");

        // quantize_input
        out.push_str(
            "int8_t blitzed_quantize_input(float raw_value) {\n\
             \x20\x20\x20\x20float normalized = raw_value / INPUT_MAX;\n\
             \x20\x20\x20\x20if (normalized > 1.0f) normalized = 1.0f;\n\
             \x20\x20\x20\x20if (normalized < -1.0f) normalized = -1.0f;\n\
             \x20\x20\x20\x20int32_t q = (int32_t)(normalized / INPUT_SCALE) + INPUT_ZERO_POINT;\n\
             \x20\x20\x20\x20if (q > 127) q = 127;\n\
             \x20\x20\x20\x20if (q < -128) q = -128;\n\
             \x20\x20\x20\x20return (int8_t)q;\n\
             }\n\n",
        );

        // dequantize_output
        let last_layer = weights.layers.last();
        let last_scale =
            last_layer.map_or("0.01f".to_string(), |l| format!("{}_output_scale", l.name));
        let last_zp =
            last_layer.map_or("0".to_string(), |l| format!("{}_output_zero_point", l.name));
        out.push_str(&format!(
            "float blitzed_dequantize_output(int8_t value) {{\n\
             \x20\x20\x20\x20return ((float)value - {lzp}) * {ls};\n\
             }}\n\n",
            ls = last_scale,
            lzp = last_zp,
        ));

        // argmax
        out.push_str(
            "int blitzed_argmax(const int8_t* output, int len) {\n\
             \x20\x20\x20\x20int max_idx = 0;\n\
             \x20\x20\x20\x20for (int i = 1; i < len; i++) {\n\
             \x20\x20\x20\x20\x20\x20\x20\x20if (output[i] > output[max_idx]) max_idx = i;\n\
             \x20\x20\x20\x20}\n\
             \x20\x20\x20\x20return max_idx;\n\
             }\n",
        );

        out
    }

    fn gen_main_c(&self, weights: &QuantizedModelWeights) -> String {
        let num_classes = weights.num_classes;

        format!(
            r#"// Generated by Blitzed v{version}
// ESP32 inference demo with real sensor input

#include <stdio.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <esp_log.h>
#include <esp_timer.h>
#include <esp_system.h>
#include "blitzed_inference.h"
#include "blitzed_model_weights.h"

static const char* TAG = "blitzed";

static void run_benchmark(int iterations) {{
    int8_t input = 0;
    int8_t output[MODEL_OUTPUT_SIZE];
    int64_t total_us = 0;
    int64_t min_us = INT64_MAX;
    int64_t max_us = 0;

    for (int i = 0; i < iterations; i++) {{
        input = blitzed_quantize_input((float)(i % 400 - 200));
        int64_t start = esp_timer_get_time();
        blitzed_model_predict(&input, 1, output, MODEL_OUTPUT_SIZE);
        int64_t elapsed = esp_timer_get_time() - start;
        total_us += elapsed;
        if (elapsed < min_us) min_us = elapsed;
        if (elapsed > max_us) max_us = elapsed;
    }}

    ESP_LOGI(TAG, "=== Benchmark: %d iterations ===", iterations);
    ESP_LOGI(TAG, "  Mean: %lld us", total_us / iterations);
    ESP_LOGI(TAG, "  Min:  %lld us", min_us);
    ESP_LOGI(TAG, "  Max:  %lld us", max_us);
    ESP_LOGI(TAG, "  Free heap: %lu bytes", (unsigned long)esp_get_free_heap_size());
}}

void app_main(void) {{
    ESP_LOGI(TAG, "Blitzed v{version} — INT8 inference on ESP32");
    ESP_LOGI(TAG, "Model: {num_classes} classes, %d input, %d output",
             MODEL_INPUT_SIZE, MODEL_OUTPUT_SIZE);
    ESP_LOGI(TAG, "Free heap at start: %lu bytes", (unsigned long)esp_get_free_heap_size());

    blitzed_model_init();

    // Run benchmark first
    run_benchmark(10000);

    // Continuous inference loop using hall sensor
    ESP_LOGI(TAG, "Starting continuous inference (hall sensor)...");
    while (1) {{
        int hall_value = hall_sensor_read();
        int8_t input = blitzed_quantize_input((float)hall_value);
        int8_t output[MODEL_OUTPUT_SIZE];

        int64_t start = esp_timer_get_time();
        blitzed_model_predict(&input, 1, output, MODEL_OUTPUT_SIZE);
        int64_t elapsed_us = esp_timer_get_time() - start;

        int class_id = blitzed_argmax(output, MODEL_OUTPUT_SIZE);
        const char* label = (class_id < NUM_CLASSES) ? class_labels[class_id] : "unknown";

        ESP_LOGI(TAG, "Hall: %d -> %s (raw: [%d,%d,%d]) %lld us",
                 hall_value, label,
                 output[0], output[1], output[2 < MODEL_OUTPUT_SIZE ? 2 : MODEL_OUTPUT_SIZE - 1],
                 elapsed_us);

        vTaskDelay(pdMS_TO_TICKS(500));
    }}
}}
"#,
            version = crate::VERSION,
            num_classes = num_classes,
        )
    }
}

// Legacy CodeGenerator trait implementation for backwards compatibility
// Uses a synthetic model with placeholder weights
impl CodeGenerator for Esp32CodeGen {
    fn generate(&self, model: &Model, output_dir: &Path) -> Result<GeneratedCode> {
        // Build a minimal quantized weights struct from model metadata
        // so the old interface still works (generates a template project)
        let info = model.info();
        let input_size: usize = info
            .input_shapes
            .first()
            .map_or(1, |s| s.iter().product::<i64>() as usize);
        let output_size: usize = info
            .output_shapes
            .first()
            .map_or(1, |s| s.iter().product::<i64>() as usize);

        let placeholder = QuantizedModelWeights {
            layers: vec![QuantizedLayerWeights {
                name: "placeholder".to_string(),
                layer_type: LayerType::Dense,
                input_size,
                output_size,
                weights_int8: vec![0i8; input_size * output_size],
                bias_int32: vec![0i32; output_size],
                weight_scale: 0.01,
                weight_zero_point: 0,
                output_scale: 0.01,
                output_zero_point: 0,
                has_relu: false,
            }],
            input_scale: 0.003921568,
            input_zero_point: 0,
            input_min: -1.0,
            input_max: 1.0,
            num_classes: output_size,
            class_labels: (0..output_size).map(|i| format!("class_{}", i)).collect(),
        };

        self.generate_from_weights(&placeholder, output_dir)
    }

    fn target_name(&self) -> &'static str {
        "esp32"
    }

    fn dependencies(&self) -> Vec<String> {
        vec!["ESP-IDF v5.x".to_string()]
    }
}

impl Default for Esp32CodeGen {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{LayerType, ModelData, ModelFormat, ModelInfo, QuantizedModelWeights};
    use crate::Model;

    fn create_test_model() -> Model {
        let layers = vec![crate::model::LayerInfo {
            name: "fc1".to_string(),
            layer_type: "linear".to_string(),
            input_shape: vec![1, 16],
            output_shape: vec![1, 8],
            parameter_count: 136,
            flops: 128,
        }];
        let info = ModelInfo {
            format: ModelFormat::PyTorch,
            input_shapes: vec![vec![1, 16]],
            output_shapes: vec![vec![1, 8]],
            parameter_count: 136,
            model_size_bytes: 544,
            operations_count: 128,
            layers,
        };
        Model {
            info,
            data: ModelData::Raw(vec![0u8; 544]),
        }
    }

    fn create_test_quantized_weights() -> QuantizedModelWeights {
        QuantizedModelWeights {
            layers: vec![
                QuantizedLayerWeights {
                    name: "layer1".to_string(),
                    layer_type: LayerType::Dense,
                    input_size: 1,
                    output_size: 4,
                    weights_int8: vec![10, -20, 30, -5],
                    bias_int32: vec![100, -200, 50, 0],
                    weight_scale: 0.005,
                    weight_zero_point: 0,
                    output_scale: 0.01,
                    output_zero_point: 0,
                    has_relu: true,
                },
                QuantizedLayerWeights {
                    name: "layer2".to_string(),
                    layer_type: LayerType::Dense,
                    input_size: 4,
                    output_size: 3,
                    weights_int8: vec![5, -10, 15, 20, -25, 30, 35, -40, 45, 50, -55, 60],
                    bias_int32: vec![10, -20, 30],
                    weight_scale: 0.004,
                    weight_zero_point: 0,
                    output_scale: 0.008,
                    output_zero_point: 0,
                    has_relu: false,
                },
            ],
            input_scale: 0.003921568,
            input_zero_point: 0,
            input_min: -200.0,
            input_max: 200.0,
            num_classes: 3,
            class_labels: vec![
                "normal".to_string(),
                "magnet_near".to_string(),
                "magnet_far".to_string(),
            ],
        }
    }

    #[test]
    fn test_esp32_codegen_new() {
        let _ = Esp32CodeGen::new();
    }

    #[test]
    fn test_esp32_generate_from_weights() {
        let gen = Esp32CodeGen::new();
        let weights = create_test_quantized_weights();
        let dir = std::env::temp_dir().join(format!("blitzed_esp32_real_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);

        let result = gen.generate_from_weights(&weights, &dir);
        assert!(
            result.is_ok(),
            "generate_from_weights failed: {:?}",
            result.err()
        );

        let generated = result.unwrap();

        // Verify files exist
        assert!(dir.join("CMakeLists.txt").exists());
        assert!(dir.join("sdkconfig.defaults").exists());
        assert!(dir.join("main/CMakeLists.txt").exists());
        assert!(dir.join("main/blitzed_model_weights.h").exists());
        assert!(dir.join("main/blitzed_inference.h").exists());
        assert!(dir.join("main/blitzed_inference.c").exists());
        assert!(dir.join("main/main.c").exists());

        // Verify content has real weights
        let weights_h = std::fs::read_to_string(dir.join("main/blitzed_model_weights.h")).unwrap();
        assert!(weights_h.contains("layer1_weights"));
        assert!(weights_h.contains("layer2_weights"));
        assert!(weights_h.contains("10, -20, 30, -5")); // actual weight values
        assert!(weights_h.contains("class_labels"));
        assert!(weights_h.contains("\"normal\""));

        // Verify inference has real layer-by-layer code
        let inference_c = std::fs::read_to_string(dir.join("main/blitzed_inference.c")).unwrap();
        assert!(inference_c.contains("layer1_bias[j]"));
        assert!(inference_c.contains("layer2_bias[j]"));
        assert!(inference_c.contains("layer1_weight_scale"));

        // Verify main/CMakeLists.txt has idf_component_register
        let main_cmake = std::fs::read_to_string(dir.join("main/CMakeLists.txt")).unwrap();
        assert!(main_cmake.contains("idf_component_register"));

        // Verify implementation_file is non-empty
        assert!(!generated.implementation_file.is_empty());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_esp32_legacy_generate() {
        let gen = Esp32CodeGen::new();
        let model = create_test_model();
        let dir = std::env::temp_dir().join(format!("blitzed_esp32_legacy_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let result = gen.generate(&model, &dir);
        assert!(result.is_ok());

        let generated = result.unwrap();
        assert!(!generated.implementation_file.is_empty());
        assert!(generated
            .implementation_file
            .contains("blitzed_model_predict"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_esp32_target_name() {
        let gen = Esp32CodeGen::new();
        assert_eq!(gen.target_name(), "esp32");
    }

    #[test]
    fn test_esp32_dependencies() {
        let gen = Esp32CodeGen::new();
        let deps = gen.dependencies();
        assert!(!deps.is_empty());
    }

    // ---------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------

    /// Build a realistic 2-layer model: Dense(1,16)+ReLU → Dense(16,3)
    fn create_two_layer_weights() -> QuantizedModelWeights {
        // layer1 weights: 1 input × 16 outputs
        let layer1_weights: Vec<i8> = (0..16_i8)
            .map(|i| if i % 2 == 0 { i + 1 } else { -(i + 1) })
            .collect();
        // layer2 weights: 16 inputs × 3 outputs = 48 values
        let layer2_weights: Vec<i8> = (0..48_i8)
            .map(|i| if i % 3 == 0 { i + 2 } else { -(i + 2) })
            .collect();

        QuantizedModelWeights {
            layers: vec![
                QuantizedLayerWeights {
                    name: "dense1".to_string(),
                    layer_type: LayerType::Dense,
                    input_size: 1,
                    output_size: 16,
                    weights_int8: layer1_weights,
                    bias_int32: (0..16).map(|i| i * 10).collect(),
                    weight_scale: 0.0078125,
                    weight_zero_point: 0,
                    output_scale: 0.015625,
                    output_zero_point: 0,
                    has_relu: true,
                },
                QuantizedLayerWeights {
                    name: "dense2".to_string(),
                    layer_type: LayerType::Dense,
                    input_size: 16,
                    output_size: 3,
                    weights_int8: layer2_weights,
                    bias_int32: vec![5, -10, 15],
                    weight_scale: 0.00390625,
                    weight_zero_point: 0,
                    output_scale: 0.0078125,
                    output_zero_point: 0,
                    has_relu: false,
                },
            ],
            input_scale: 0.003921568,
            input_zero_point: 0,
            input_min: -200.0,
            input_max: 200.0,
            num_classes: 3,
            class_labels: vec![
                "class_a".to_string(),
                "class_b".to_string(),
                "class_c".to_string(),
            ],
        }
    }

    fn unique_dir(suffix: &str) -> std::path::PathBuf {
        use std::time::{SystemTime, UNIX_EPOCH};
        let ts = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.subsec_nanos())
            .unwrap_or(0);
        std::env::temp_dir().join(format!(
            "blitzed_esp32_{}_{}_{}",
            suffix,
            std::process::id(),
            ts
        ))
    }

    // ---------------------------------------------------------------
    // 1. generate_from_weights — all expected files are created
    // ---------------------------------------------------------------

    #[test]
    fn test_generate_from_weights_creates_all_files() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("all_files");
        let _ = std::fs::remove_dir_all(&dir);

        let result = gen.generate_from_weights(&weights, &dir);
        assert!(
            result.is_ok(),
            "generate_from_weights failed: {:?}",
            result.err()
        );

        // All seven files must exist
        let expected = [
            "CMakeLists.txt",
            "sdkconfig.defaults",
            "main/CMakeLists.txt",
            "main/blitzed_model_weights.h",
            "main/blitzed_inference.h",
            "main/blitzed_inference.c",
            "main/main.c",
        ];
        for rel in &expected {
            assert!(dir.join(rel).exists(), "Missing expected file: {}", rel);
        }

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_generate_from_weights_returns_nonempty_generated_code() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("nonempty");
        let _ = std::fs::remove_dir_all(&dir);

        let generated = gen.generate_from_weights(&weights, &dir).unwrap();

        assert!(!generated.implementation_file.is_empty());
        assert!(!generated.header_file.as_deref().unwrap_or("").is_empty());
        assert!(!generated.example_file.as_deref().unwrap_or("").is_empty());
        assert!(!generated.build_config.as_deref().unwrap_or("").is_empty());
        assert!(!generated.dependencies.is_empty());

        let _ = std::fs::remove_dir_all(&dir);
    }

    // ---------------------------------------------------------------
    // 2. Weights header — actual INT8 values and defines
    // ---------------------------------------------------------------

    #[test]
    fn test_weights_header_contains_actual_int8_values() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("weights_values");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let header = std::fs::read_to_string(dir.join("main/blitzed_model_weights.h")).unwrap();

        // The first few weight bytes of layer1 are known — verify they appear
        // layer1_weights: [1, -2, 3, -4, 5, -6, 7, -8, 9, -10, 11, -12, 13, -14, 15, -16]
        assert!(
            header.contains("dense1_weights"),
            "weights header missing dense1_weights"
        );
        assert!(
            header.contains("dense2_weights"),
            "weights header missing dense2_weights"
        );
        // Spot-check a known value from layer1 (first element = 1)
        assert!(
            header.contains("1, "),
            "weights header missing known INT8 value '1,'"
        );
        // Spot-check a negative value that can only come from layer1 weights
        assert!(
            header.contains("-2, "),
            "weights header missing known INT8 value '-2,'"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_weights_header_layer_size_defines_match_input() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("size_defines");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let header = std::fs::read_to_string(dir.join("main/blitzed_model_weights.h")).unwrap();

        // DENSE1_INPUT_SIZE = 1, DENSE1_OUTPUT_SIZE = 16
        assert!(
            header.contains("DENSE1_INPUT_SIZE 1"),
            "missing DENSE1_INPUT_SIZE 1"
        );
        assert!(
            header.contains("DENSE1_OUTPUT_SIZE 16"),
            "missing DENSE1_OUTPUT_SIZE 16"
        );
        // DENSE2_INPUT_SIZE = 16, DENSE2_OUTPUT_SIZE = 3
        assert!(
            header.contains("DENSE2_INPUT_SIZE 16"),
            "missing DENSE2_INPUT_SIZE 16"
        );
        assert!(
            header.contains("DENSE2_OUTPUT_SIZE 3"),
            "missing DENSE2_OUTPUT_SIZE 3"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_weights_header_num_classes_matches_input() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("num_classes");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let header = std::fs::read_to_string(dir.join("main/blitzed_model_weights.h")).unwrap();

        assert!(
            header.contains("NUM_CLASSES 3"),
            "missing NUM_CLASSES 3, got: {}",
            &header[..header.len().min(500)]
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_weights_header_class_labels_array_present() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("class_labels");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let header = std::fs::read_to_string(dir.join("main/blitzed_model_weights.h")).unwrap();

        assert!(
            header.contains("class_labels"),
            "missing class_labels array"
        );
        assert!(header.contains("\"class_a\""), "missing label class_a");
        assert!(header.contains("\"class_b\""), "missing label class_b");
        assert!(header.contains("\"class_c\""), "missing label class_c");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_weights_header_scale_and_zero_point_constants_present() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("scale_zp");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let header = std::fs::read_to_string(dir.join("main/blitzed_model_weights.h")).unwrap();

        // Input quantization params
        assert!(header.contains("INPUT_SCALE"), "missing INPUT_SCALE");
        assert!(
            header.contains("INPUT_ZERO_POINT"),
            "missing INPUT_ZERO_POINT"
        );

        // Per-layer scales and zero points
        assert!(
            header.contains("dense1_weight_scale"),
            "missing dense1_weight_scale"
        );
        assert!(
            header.contains("dense1_weight_zero_point"),
            "missing dense1_weight_zero_point"
        );
        assert!(
            header.contains("dense1_output_scale"),
            "missing dense1_output_scale"
        );
        assert!(
            header.contains("dense1_output_zero_point"),
            "missing dense1_output_zero_point"
        );
        assert!(
            header.contains("dense2_weight_scale"),
            "missing dense2_weight_scale"
        );
        assert!(
            header.contains("dense2_output_scale"),
            "missing dense2_output_scale"
        );

        // Verify the actual float value round-trips (not zeros)
        assert!(
            header.contains("0.0078125"),
            "dense1 weight_scale value 0.0078125 not in header"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    // ---------------------------------------------------------------
    // 3. Inference implementation — structure and correctness
    // ---------------------------------------------------------------

    #[test]
    fn test_inference_c_contains_int8_matmul_pattern() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("matmul");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let inference = std::fs::read_to_string(dir.join("main/blitzed_inference.c")).unwrap();

        // INT8 accumulation into int32_t acc
        assert!(
            inference.contains("int32_t acc"),
            "missing int32_t accumulator"
        );
        // Cast pattern for INT8 multiply-accumulate
        assert!(
            inference.contains("(int32_t)"),
            "missing int32_t cast in matmul"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_inference_c_includes_esp_timer_header() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("esp_timer");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        // esp_timer.h is included in main.c (the demo), not inference.c
        let main_c = std::fs::read_to_string(dir.join("main/main.c")).unwrap();
        assert!(
            main_c.contains("esp_timer.h"),
            "main.c missing #include <esp_timer.h>"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_inference_c_has_blitzed_model_predict_function() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("predict_fn");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let inference = std::fs::read_to_string(dir.join("main/blitzed_inference.c")).unwrap();

        assert!(
            inference.contains("blitzed_model_predict"),
            "inference.c missing blitzed_model_predict"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_inference_c_has_relu_in_hidden_layer() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights(); // dense1 has has_relu = true
        let dir = unique_dir("relu");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let inference = std::fs::read_to_string(dir.join("main/blitzed_inference.c")).unwrap();

        assert!(
            inference.contains("ReLU"),
            "inference.c missing ReLU comment/annotation"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_inference_c_has_quantize_and_dequantize_functions() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("quant_fns");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let inference = std::fs::read_to_string(dir.join("main/blitzed_inference.c")).unwrap();

        assert!(
            inference.contains("blitzed_quantize_input"),
            "inference.c missing blitzed_quantize_input"
        );
        assert!(
            inference.contains("blitzed_dequantize_output"),
            "inference.c missing blitzed_dequantize_output"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    // ---------------------------------------------------------------
    // 4. main.c — sensor reading, benchmark, inference loop
    // ---------------------------------------------------------------

    #[test]
    fn test_main_c_has_sensor_reading_code() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("sensor");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let main_c = std::fs::read_to_string(dir.join("main/main.c")).unwrap();

        assert!(
            main_c.contains("hall_sensor_read"),
            "main.c missing hall_sensor_read call"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_main_c_has_benchmark_function() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("benchmark_fn");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let main_c = std::fs::read_to_string(dir.join("main/main.c")).unwrap();

        assert!(
            main_c.contains("run_benchmark"),
            "main.c missing run_benchmark function"
        );
        assert!(
            main_c.contains("Benchmark"),
            "main.c missing benchmark log output"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_main_c_has_inference_loop() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("inf_loop");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let main_c = std::fs::read_to_string(dir.join("main/main.c")).unwrap();

        assert!(
            main_c.contains("while (1)"),
            "main.c missing inference while loop"
        );
        assert!(
            main_c.contains("blitzed_model_predict"),
            "main.c missing blitzed_model_predict call"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    // ---------------------------------------------------------------
    // 5. CMakeLists files
    // ---------------------------------------------------------------

    #[test]
    fn test_project_cmake_includes_idf_path_line() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("proj_cmake");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let cmake = std::fs::read_to_string(dir.join("CMakeLists.txt")).unwrap();

        assert!(
            cmake.contains("include($ENV{IDF_PATH}/tools/cmake/project.cmake)"),
            "project CMakeLists.txt missing IDF_PATH include"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_main_cmake_has_idf_component_register() {
        let gen = Esp32CodeGen::new();
        let weights = create_two_layer_weights();
        let dir = unique_dir("main_cmake");
        let _ = std::fs::remove_dir_all(&dir);
        gen.generate_from_weights(&weights, &dir).unwrap();

        let cmake = std::fs::read_to_string(dir.join("main/CMakeLists.txt")).unwrap();

        assert!(
            cmake.contains("idf_component_register"),
            "main/CMakeLists.txt missing idf_component_register"
        );
        assert!(
            cmake.contains("blitzed_inference.c"),
            "main/CMakeLists.txt missing blitzed_inference.c in SRCS"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    // ---------------------------------------------------------------
    // 6. Edge cases
    // ---------------------------------------------------------------

    #[test]
    fn test_single_layer_model() {
        let gen = Esp32CodeGen::new();
        let weights = QuantizedModelWeights {
            layers: vec![QuantizedLayerWeights {
                name: "output".to_string(),
                layer_type: LayerType::Dense,
                input_size: 4,
                output_size: 2,
                weights_int8: vec![1, -1, 2, -2, 3, -3, 4, -4],
                bias_int32: vec![10, -10],
                weight_scale: 0.01,
                weight_zero_point: 0,
                output_scale: 0.02,
                output_zero_point: 0,
                has_relu: false,
            }],
            input_scale: 0.003921568,
            input_zero_point: 0,
            input_min: -1.0,
            input_max: 1.0,
            num_classes: 2,
            class_labels: vec!["yes".to_string(), "no".to_string()],
        };
        let dir = unique_dir("single_layer");
        let _ = std::fs::remove_dir_all(&dir);

        let result = gen.generate_from_weights(&weights, &dir);
        assert!(
            result.is_ok(),
            "single-layer model failed: {:?}",
            result.err()
        );

        // All files still exist
        assert!(dir.join("CMakeLists.txt").exists());
        assert!(dir.join("main/blitzed_model_weights.h").exists());
        assert!(dir.join("main/blitzed_inference.c").exists());

        let header = std::fs::read_to_string(dir.join("main/blitzed_model_weights.h")).unwrap();
        assert!(header.contains("OUTPUT_INPUT_SIZE 4"));
        assert!(header.contains("OUTPUT_OUTPUT_SIZE 2"));
        assert!(header.contains("NUM_CLASSES 2"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_empty_class_labels() {
        let gen = Esp32CodeGen::new();
        let weights = QuantizedModelWeights {
            layers: vec![QuantizedLayerWeights {
                name: "fc".to_string(),
                layer_type: LayerType::Dense,
                input_size: 2,
                output_size: 1,
                weights_int8: vec![10, -10],
                bias_int32: vec![0],
                weight_scale: 0.01,
                weight_zero_point: 0,
                output_scale: 0.01,
                output_zero_point: 0,
                has_relu: false,
            }],
            input_scale: 0.01,
            input_zero_point: 0,
            input_min: -1.0,
            input_max: 1.0,
            num_classes: 0,
            class_labels: vec![],
        };
        let dir = unique_dir("empty_labels");
        let _ = std::fs::remove_dir_all(&dir);

        // Should not panic — empty labels are valid (uncommon but legal)
        let result = gen.generate_from_weights(&weights, &dir);
        assert!(
            result.is_ok(),
            "empty class_labels caused failure: {:?}",
            result.err()
        );

        let header = std::fs::read_to_string(dir.join("main/blitzed_model_weights.h")).unwrap();
        assert!(
            header.contains("NUM_CLASSES 0"),
            "NUM_CLASSES should be 0 for empty labels"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_large_model_many_weights() {
        let gen = Esp32CodeGen::new();
        // 128-input → 64 hidden → 10 output — relatively large for a microcontroller
        let layer1_weights: Vec<i8> = (0..128 * 64).map(|i| (i % 127) as i8).collect();
        let layer2_weights: Vec<i8> = (0..64 * 10).map(|i| -((i % 127) as i8)).collect();

        let weights = QuantizedModelWeights {
            layers: vec![
                QuantizedLayerWeights {
                    name: "hidden".to_string(),
                    layer_type: LayerType::Dense,
                    input_size: 128,
                    output_size: 64,
                    weights_int8: layer1_weights,
                    bias_int32: vec![0i32; 64],
                    weight_scale: 0.01,
                    weight_zero_point: 0,
                    output_scale: 0.01,
                    output_zero_point: 0,
                    has_relu: true,
                },
                QuantizedLayerWeights {
                    name: "logits".to_string(),
                    layer_type: LayerType::Dense,
                    input_size: 64,
                    output_size: 10,
                    weights_int8: layer2_weights,
                    bias_int32: vec![0i32; 10],
                    weight_scale: 0.01,
                    weight_zero_point: 0,
                    output_scale: 0.01,
                    output_zero_point: 0,
                    has_relu: false,
                },
            ],
            input_scale: 0.003921568,
            input_zero_point: 0,
            input_min: -1.0,
            input_max: 1.0,
            num_classes: 10,
            class_labels: (0..10).map(|i| format!("digit_{}", i)).collect(),
        };

        let dir = unique_dir("large_model");
        let _ = std::fs::remove_dir_all(&dir);

        let result = gen.generate_from_weights(&weights, &dir);
        assert!(result.is_ok(), "large model failed: {:?}", result.err());

        let header = std::fs::read_to_string(dir.join("main/blitzed_model_weights.h")).unwrap();
        assert!(header.contains("HIDDEN_INPUT_SIZE 128"));
        assert!(header.contains("HIDDEN_OUTPUT_SIZE 64"));
        assert!(header.contains("LOGITS_INPUT_SIZE 64"));
        assert!(header.contains("LOGITS_OUTPUT_SIZE 10"));
        assert!(header.contains("NUM_CLASSES 10"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    // ---------------------------------------------------------------
    // 7. CodeGenerator trait — backward compatibility
    // ---------------------------------------------------------------

    #[test]
    fn test_legacy_generate_returns_ok() {
        let gen = Esp32CodeGen::new();
        let model = create_test_model();
        let dir = unique_dir("legacy_ok");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let result = gen.generate(&model, &dir);
        assert!(result.is_ok(), "legacy generate failed: {:?}", result.err());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_legacy_generate_produces_predict_function() {
        let gen = Esp32CodeGen::new();
        let model = create_test_model();
        let dir = unique_dir("legacy_predict");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        let generated = gen.generate(&model, &dir).unwrap();
        assert!(generated
            .implementation_file
            .contains("blitzed_model_predict"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_legacy_generate_creates_all_files() {
        let gen = Esp32CodeGen::new();
        let model = create_test_model();
        let dir = unique_dir("legacy_files");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        gen.generate(&model, &dir).unwrap();

        assert!(
            dir.join("CMakeLists.txt").exists(),
            "missing CMakeLists.txt"
        );
        assert!(
            dir.join("main/blitzed_inference.c").exists(),
            "missing inference.c"
        );
        assert!(dir.join("main/main.c").exists(), "missing main.c");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_legacy_generate_respects_model_input_output_shapes() {
        let gen = Esp32CodeGen::new();
        let model = create_test_model(); // input 16, output 8
        let dir = unique_dir("legacy_shapes");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        gen.generate(&model, &dir).unwrap();

        let inference_h = std::fs::read_to_string(dir.join("main/blitzed_inference.h")).unwrap();
        assert!(
            inference_h.contains("MODEL_INPUT_SIZE 16"),
            "inference.h MODEL_INPUT_SIZE should be 16"
        );
        assert!(
            inference_h.contains("MODEL_OUTPUT_SIZE 8"),
            "inference.h MODEL_OUTPUT_SIZE should be 8"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_default_impl_equals_new() {
        let _a = Esp32CodeGen::new();
        let _b = Esp32CodeGen;
        assert_eq!(_a.target_name(), _b.target_name());
    }

    #[test]
    fn test_dependencies_contains_esp_idf() {
        let gen = Esp32CodeGen::new();
        let deps = gen.dependencies();
        assert!(
            deps.iter().any(|d| d.contains("ESP-IDF")),
            "dependencies should mention ESP-IDF, got: {:?}",
            deps
        );
    }
}
