// Copyright 2025 Gibran Rodriguez <brangi000@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! ESP32-specific code generator

use super::{CodeGenerator, GeneratedCode};
use crate::{Model, Result};
use std::path::Path;

/// ESP32 code generator
pub struct Esp32CodeGen;

impl Esp32CodeGen {
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl CodeGenerator for Esp32CodeGen {
    fn generate(&self, _model: &Model, output_dir: &Path) -> Result<GeneratedCode> {
        std::fs::create_dir_all(output_dir)?;

        let main_content = format!(
            r#"// Generated by Blitzed v{}
// ESP32 model deployment

#include <stdio.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <esp_log.h>
#include <esp_timer.h>
#include "blitzed_model.h"

static const char* TAG = "blitzed_model";

void inference_task(void* params) {{
    model_input_t* input = (model_input_t*)malloc(MODEL_INPUT_SIZE * sizeof(model_input_t));
    model_output_t* output = (model_output_t*)malloc(MODEL_OUTPUT_SIZE * sizeof(model_output_t));
    
    if (!input || !output) {{
        ESP_LOGE(TAG, "Failed to allocate memory for inference");
        vTaskDelete(NULL);
        return;
    }}

    while (1) {{
        // Generate sample input
        for (int i = 0; i < MODEL_INPUT_SIZE; i++) {{
            input[i] = (model_input_t)(esp_random() % 256 - 128);
        }}

        ESP_LOGI(TAG, "Running inference...");
        int64_t start_time = esp_timer_get_time();
        
        int result = model_predict(input, output);
        
        int64_t duration = esp_timer_get_time() - start_time;
        
        if (result == 0) {{
            ESP_LOGI(TAG, "Inference completed in %lld μs", duration);
            ESP_LOGI(TAG, "Top output: %d", output[0]);
        }} else {{
            ESP_LOGE(TAG, "Inference failed");
        }}
        
        vTaskDelay(pdMS_TO_TICKS(5000)); // Wait 5 seconds
    }}
    
    free(input);
    free(output);
    vTaskDelete(NULL);
}}

void app_main() {{
    ESP_LOGI(TAG, "Blitzed Model on ESP32");
    
    if (model_init() != 0) {{
        ESP_LOGE(TAG, "Model initialization failed");
        return;
    }}
    
    ESP_LOGI(TAG, "Model initialized successfully");
    
    // Create inference task
    xTaskCreate(inference_task, "inference", 8192, NULL, 5, NULL);
}}
"#,
            crate::VERSION
        );

        let cmake_content = format!(
            r"# Generated by Blitzed v{}
# ESP32 CMakeLists.txt

cmake_minimum_required(VERSION 3.5)

include($ENV{{IDF_PATH}}/tools/cmake/project.cmake)
project(blitzed_model)
",
            crate::VERSION
        );

        let main_path = output_dir.join("main.c");
        let cmake_path = output_dir.join("CMakeLists.txt");

        std::fs::write(&main_path, &main_content)?;
        std::fs::write(&cmake_path, &cmake_content)?;

        Ok(GeneratedCode {
            implementation_file: main_content,
            header_file: None,
            example_file: Some(main_path.to_string_lossy().to_string()),
            build_config: Some(cmake_path.to_string_lossy().to_string()),
            dependencies: vec!["ESP-IDF".to_string()],
        })
    }

    fn target_name(&self) -> &'static str {
        "esp32"
    }

    fn dependencies(&self) -> Vec<String> {
        vec!["ESP-IDF".to_string()]
    }
}

impl Default for Esp32CodeGen {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{LayerInfo, ModelData, ModelFormat, ModelInfo};
    use crate::Model;

    fn create_test_model() -> Model {
        let layers = vec![LayerInfo {
            name: "fc1".to_string(),
            layer_type: "linear".to_string(),
            input_shape: vec![1, 16],
            output_shape: vec![1, 8],
            parameter_count: 136,
            flops: 128,
        }];
        let info = ModelInfo {
            format: ModelFormat::PyTorch,
            input_shapes: vec![vec![1, 16]],
            output_shapes: vec![vec![1, 8]],
            parameter_count: 136,
            model_size_bytes: 544,
            operations_count: 128,
            layers,
        };
        Model {
            info,
            data: ModelData::Raw(vec![0u8; 544]),
        }
    }

    #[test]
    fn test_esp32_codegen_new() {
        let _ = Esp32CodeGen::new();
    }

    #[test]
    fn test_esp32_generate() {
        let gen = Esp32CodeGen::new();
        let model = create_test_model();
        let dir = std::env::temp_dir().join(format!("blitzed_test_{}", std::process::id()));
        std::fs::create_dir_all(&dir)
            .unwrap_or_else(|_| panic!("Failed to create temp directory: {}", dir.display()));

        let result = gen.generate(&model, &dir);
        assert!(result.is_ok());

        let generated = result.unwrap();
        assert!(!generated.implementation_file.is_empty());
        assert!(generated.implementation_file.contains("ESP32"));

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_esp32_target_name() {
        let gen = Esp32CodeGen::new();
        assert_eq!(gen.target_name(), "esp32");
    }

    #[test]
    fn test_esp32_dependencies() {
        let gen = Esp32CodeGen::new();
        let deps = gen.dependencies();
        assert!(!deps.is_empty());
    }
}
