// Auto-generated by tools/train_touch_gesture_classifier.py
// Model: 2-layer dense network for ESP32 touch gesture classification
// Architecture: Dense(20, 32) + ReLU + Dense(32, 5)
// Input: 20 float features from 1.5s touch window (75 steps at 50Hz, 4 pads)
// Touch pads: GPIO 4 (pad0), GPIO 12 (pad1), GPIO 14 (pad2), GPIO 27 (pad3)
// Total parameters: 837
// Quantized model size: 948 bytes
// Quantization: calibrated INT8 PTQ (output scales from activation statistics)

#ifndef BLITZED_MODEL_WEIGHTS_H
#define BLITZED_MODEL_WEIGHTS_H

#include <stdint.h>

// Layer 1: Dense(20, 32) + ReLU
#define LAYER1_INPUT_SIZE  20
#define LAYER1_OUTPUT_SIZE 32

// Weights stored row-major: layer1_weights[input_idx * LAYER1_OUTPUT_SIZE + output_idx]
static const int8_t layer1_weights[640] = {
    61, 3, -49, -23, 33, -7, 93, 101, 29, -17, 100, 5,
    68, 33, -10, 78, 66, 24, 27, 41, -78, 3, -20, -38,
    21, 42, 39, -71, -1, 28, 55, 70, -48, 55, 36, 71,
    34, 55, 98, -3, 6, 4, 35, -2, 19, -2, -64, -4,
    51, -19, 14, 19, 67, 38, -13, -22, -23, -12, 20, 16,
    48, 42, 46, 36, 34, 42, -27, 24, -5, 33, 0, -14,
    41, 55, -44, -6, -2, -25, 51, 124, 37, 0, 25, -12,
    25, 18, 70, 29, 9, 9, -32, 9, 59, -8, 56, 19,
    -5, -19, -38, 3, -10, 1, -34, 19, -30, -18, 54, 37,
    -10, 4, 70, -2, 8, 44, 21, -3, 13, 0, 90, 0,
    11, -1, -10, 29, 13, 44, -17, 30, 68, -36, -8, 40,
    5, 30, 53, 118, 47, -16, 93, 53, -17, 24, -1, 26,
    91, 31, 31, 24, -72, -14, -44, -65, 84, 7, -28, -46,
    25, 48, 40, 37, -32, 58, 22, -25, 0, 64, 58, 50,
    -8, 43, 5, 50, 3, -15, -30, 8, 45, 1, -25, 0,
    2, 26, -7, 5, -26, -30, 54, -32, -14, 35, 48, -27,
    13, 6, 8, -1, -48, 39, 42, -19, -31, 16, -21, 32,
    8, 2, 18, 102, -4, -30, 20, 44, 63, -30, 63, 39,
    55, 40, 14, 32, 29, 42, 65, 28, 39, -51, -1, -28,
    -15, -25, -10, 29, -3, 20, 34, -56, -10, 14, 31, 18,
    18, -29, 26, 56, 17, 30, 63, 29, 53, -25, 30, 37,
    71, -30, -29, 19, 48, -17, -35, 33, 10, 79, 51, 104,
    12, 8, 28, -32, 22, 67, -29, 52, 90, -1, -24, 51,
    -47, 47, -28, -54, -14, 45, 8, -77, 32, -26, 45, -10,
    0, 61, 59, 19, -22, 64, 74, 15, 43, -23, 15, 40,
    47, 0, -44, 11, -2, 9, 1, -19, 7, 38, -20, -35,
    25, 47, 22, -24, -26, -19, 15, 12, 11, -26, 5, -3,
    25, -1, 44, 5, 16, 8, -5, 15, 32, 24, 57, 106,
    14, -26, 0, -11, 20, 15, 54, 50, -2, 3, -31, 58,
    34, 6, 66, -31, 57, -46, -40, -32, 7, 19, -20, -19,
    28, 35, 2, 1, -39, -16, 60, 2, -9, 34, 5, 33,
    13, -7, 36, 5, 0, 5, 21, 2, 78, 42, -12, 47,
    7, -14, -39, 27, 18, 61, 90, 91, 14, -44, 101, 26,
    43, 64, -33, -10, 49, 21, 35, -9, -17, 17, -1, -69,
    87, 46, -34, -69, 36, 28, 6, -14, 5, 3, 47, 26,
    -1, 11, 60, -10, 9, 72, -29, 85, 47, 54, -14, 1,
    53, -30, -22, 14, 13, 61, -6, -46, 10, -11, 48, -13,
    -53, -5, 55, -22, -12, -13, -15, -13, -16, 65, 17, 0,
    3, 19, 14, 20, -18, 32, 64, 81, 1, -10, 27, -5,
    -20, -20, 30, 62, 7, -1, 37, 18, 31, 8, 74, -4,
    51, -40, -2, -23, 41, -5, -45, -22, 30, 26, -18, -44,
    -3, 21, 8, 58, -30, 35, -8, 58, -2, 12, 41, 65,
    32, 6, -13, 48, -23, 45, 2, 32, 18, -12, -17, 8,
    -22, 51, 29, -39, -18, 39, -36, 69, 47, 32, 84, 81,
    4, 38, -24, -23, 14, -67, 54, 47, -4, 7, -24, 52,
    65, 64, 62, -27, 86, 30, 100, -8, 33, 54, -61, 26,
    -34, 85, 22, 61, 38, -32, 127, -65, 86, -29, -22, 82,
    -40, 83, 52, -8, 21, 10, 30, 45, -128, -60, 34, -26,
    61, -13, -13, 15, 30, 56, 51, 92, 19, 10, 44, -7,
    58, 38, -17, 63, 45, -10, 5, -11, -21, 4, -45, -62,
    8, 35, 32, -69, -16, 24, 54, -22, 1, -11, -16, 13,
    -25, 55, 38, -7, -13, -12, 42, 14, 21, 9, 34, 23,
    45, 10, 9, -12, 26, -19, -13, 8, -20, 18, -3, -18,
    6, 19, 8, -9
};

static const int32_t layer1_bias[32] = {
    -1333, 7101, 11753, -426, 9784, -6672, 3669, 7281, -1721, -6341, 10071, -5071,
    -1578, 1542, -6951, -4689, -3437, -26, -1383, 6928, 8715, 13337, -2512, 7528,
    -647, 491, 331, 6072, 6169, 760, -7180, 897
};

static const float layer1_weight_scale = 0.0083997312f;
static const int32_t layer1_weight_zero_point = 9;
// Calibrated output scale: maps post-ReLU activations to INT8 [0, 127]
static const float layer1_output_scale = 0.0231110171f;
static const int32_t layer1_output_zero_point = 0;

// Layer 2: Dense(32, 5)
#define LAYER2_INPUT_SIZE  32
#define LAYER2_OUTPUT_SIZE 5

// Weights stored row-major: layer2_weights[input_idx * LAYER2_OUTPUT_SIZE + output_idx]
static const int8_t layer2_weights[160] = {
    16, -70, -78, 9, 21, -59, -51, 62, -53, -35, -38, -98,
    90, -10, -51, -42, -22, 30, -38, -38, -57, -11, 28, 42,
    24, 41, 1, -26, -89, 43, -75, 23, -5, -114, 80, -67,
    -56, -51, -12, 127, -43, 8, 1, -16, -41, 53, -49, 4,
    -51, -58, -74, -31, -29, 29, 96, 47, 0, 23, -91, 20,
    13, -27, -2, -48, 53, -51, -14, -22, -45, 43, 94, -44,
    -73, 12, -94, 36, 98, -103, -89, 14, 19, -63, -32, -59,
    79, -43, -45, -32, 23, -5, 18, -6, 9, 0, -24, -15,
    -73, -13, 41, 4, -40, 37, 62, 14, -91, -49, -94, 54,
    18, 18, 62, 22, -43, 42, -84, -18, 38, 13, 46, -120,
    -13, -46, -75, 7, 35, -41, -3, -16, -36, -2, -12, 10,
    44, 4, 1, 16, 2, 24, 57, -128, -82, 99, -61, 14,
    -23, -58, 41, -19, -56, -8, 47, 21, -40, -109, 8, -37,
    9, -49, -37, 10
};

static const int32_t layer2_bias[5] = {
    -2790, -1937, 1757, 3202, -232
};

static const float layer2_weight_scale = 0.0116018482f;
static const int32_t layer2_weight_zero_point = -10;
// Calibrated output scale: maps output logits to INT8 [-128, 127]
static const float layer2_output_scale = 0.0694946429f;
static const int32_t layer2_output_zero_point = -47;

// Input quantization parameters
// Features are pre-normalized to [0, 1]; divide by INPUT_NORM_FACTOR (1.0) before quantizing
#define INPUT_SCALE        0.0078740157f
#define INPUT_ZERO_POINT   0
#define INPUT_NORM_FACTOR  1.0f

// Model dimensions
#define NUM_FEATURES  20
#define NUM_CLASSES   5

// Feature layout (per-pad features repeat for pads 0-3):
//   pad*4+0: touch_duration   (fraction of window touched, [0,1])
//   pad*4+1: touch_centroid   (weighted avg time position of touch, [0,1])
//   pad*4+2: mean_intensity   (avg (baseline-reading)/baseline during touch, [0,1])
//   pad*4+3: touch_count      (distinct touch-release transitions / 5, [0,1])
// Global features:
//   [16]: active_pin_count    (pads touched at all / 4, [0,1])
//   [17]: spatial_sweep       (pad_idx vs centroid correlation mapped to [0,1])
//   [18]: total_duration      (sum of per-pad durations / 4, [0,1])
//   [19]: inter_onset_interval (mean gap between pad onset times / 1.0, [0,1])

// Class labels
static const char* class_labels[NUM_CLASSES] = {
    "swipe_right",
    "swipe_left",
    "single_tap",
    "double_tap",
    "long_press"
};

// Touch pad GPIO mapping
#define TOUCH_PAD_GPIO_0   4
#define TOUCH_PAD_GPIO_1  12
#define TOUCH_PAD_GPIO_2  14
#define TOUCH_PAD_GPIO_3  27

// Calibration: threshold = 70% of baseline (touch causes reading to DROP)
#define TOUCH_THRESHOLD_RATIO 0.70f

#endif // BLITZED_MODEL_WEIGHTS_H
