// Auto-generated by tools/train_predictive_maintenance.py
// Model: 2-layer dense network for ESP32 predictive maintenance
// Architecture: Dense(4, 32) + ReLU + Dense(32, 4)
// Total parameters: 292
// Quantized model size: 400 bytes
//
// Input features (normalised before quantization):
//   [0] temperature   / 120.0  (raw °C)
//   [1] rms_accel_x   / 12.0   (raw g)
//   [2] rms_accel_y   / 12.0   (raw g)
//   [3] rms_accel_z   / 12.0   (raw g)

#ifndef BLITZED_MODEL_WEIGHTS_H
#define BLITZED_MODEL_WEIGHTS_H

#include <stdint.h>

// ---- Layer 1: Dense(4, 32) + ReLU ----
#define LAYER1_INPUT_SIZE  4
#define LAYER1_OUTPUT_SIZE 32

// Weight layout: layer1_weights[input_idx * LAYER1_OUTPUT_SIZE + output_idx]
static const int8_t layer1_weights[128] = {
    12, -24, 79, 33, 21, 104, -27, -4, 70, -23, -12, -4,
    -15, 64, 41, 26, -19, -19, 114, -14, -28, -35, 34, -62,
    -23, -41, -35, -13, -27, 86, -29, 51, -12, -13, 90, 71,
    -12, 47, -4, -21, 69, -20, -28, -6, -17, 1, 74, 23,
    12, -10, 110, -8, -37, 6, -19, -59, -14, -9, 33, -16,
    15, 83, -75, -28, -32, -24, 36, 77, -13, 68, -30, -45,
    25, -15, -21, 8, 11, -28, 77, 21, -15, 22, 127, 4,
    -45, 30, -2, -52, 30, 21, 26, 26, -3, 69, -83, 33,
    4, 21, 54, 77, -7, 74, 18, -56, 34, 3, -11, -13,
    -14, -17, 83, 52, 13, -31, 127, -15, -10, -7, -42, -49,
    -4, 22, 25, -8, 11, 59, -86, -2
};

static const int32_t layer1_bias[32] = {
    -385, 0, -4144, -7414, -231, -5065, 0, 15071, -2526, 0, 0, -41,
    0, 3350, -3262, -3895, -34, 0, -6347, 4406, 7217, -342, 9649, 25129,
    -183, 2333, 1878, 259, 2603, -4381, 16864, 8339
};

static const float layer1_weight_scale = 0.0122997340f;
static const int32_t layer1_weight_zero_point = 0;
static const float layer1_output_scale = 0.0395333807f;
static const int32_t layer1_output_zero_point = 0;

// ---- Layer 2: Dense(32, 4) ----
#define LAYER2_INPUT_SIZE  32
#define LAYER2_OUTPUT_SIZE 4

// Weight layout: layer2_weights[input_idx * LAYER2_OUTPUT_SIZE + output_idx]
static const int8_t layer2_weights[128] = {
    -11, -21, -11, -13, -21, 12, -18, -2, -67, -5, 32, 48,
    -7, -51, 22, 79, -7, 1, 0, 21, -82, 20, -2, 63,
    4, 16, 17, 2, 48, 35, -2, -68, -62, 9, 29, 17,
    11, -19, -1, -19, -1, -20, 5, 4, 13, 4, 18, 12,
    -16, -10, -21, -5, -2, 47, -7, -5, -76, -21, 38, 37,
    10, -31, 13, 36, 5, 15, -7, -14, -15, -10, -2, 16,
    -127, 23, 54, 79, 25, 14, 6, -10, 37, -14, -40, -5,
    -17, 20, 0, -5, -1, 23, -10, -56, 89, 17, 14, -119,
    18, 4, 7, 12, 8, -26, 3, -13, -8, -17, 30, -7,
    -13, 20, 19, 21, 4, -21, 22, -17, -92, -5, 24, 35,
    85, 7, -91, -28, -12, 44, 24, -33
};

static const int32_t layer2_bias[4] = {
    1264, 1072, -95, -2241
};

static const float layer2_weight_scale = 0.0188594397f;
static const int32_t layer2_weight_zero_point = 0;
static const float layer2_output_scale = 0.0007455774f;
static const int32_t layer2_output_zero_point = 0;

// ---- Input quantization parameters ----
// input_scale = 1/255 — normalised inputs in [-1, 1] map to INT8
#define INPUT_SCALE 0.0078740157f
#define INPUT_ZERO_POINT 0

// ---- Class labels ----
#define NUM_CLASSES 4
static const char* class_labels[NUM_CLASSES] = {
    "healthy",
    "warning",
    "critical",
    "shutdown_required"
};

#endif // BLITZED_MODEL_WEIGHTS_H
